### ISSUE TITLE
Workers with issues.

### ISSUE THREAD

**Issue by vdbergh** [official-stockfish/fishtest#1360] opened 2022-06-14 04:28 UTC
I am creating this issue to report workers with issues. E.g. currently.

https://tests.stockfishchess.org/actions?action=failed_task&user=Oakwen&before=1655180683.077&max_actions=100

**Comment by vondele** [comment] 2022-06-14 05:14
This worker is probably running in a bug in latest clang. https://github.com/llvm/llvm-project/issues/55377 
I see his workers are based on clang 15.

**Comment by vondele** [comment] 2022-06-14 10:21
for whatever reason the TLS might be handled differently or the code aligned properly by luck, depending on the OS.

**Comment by vdbergh** [comment] 2022-06-15 04:02
Oakwen-3cores-8708609b switched to g++ so the problem is solved.

**Comment by vdbergh** [comment] 2022-06-15 04:07
Another issue: The matches of Dantist-7cores-3e5ab901 always finish with "Finished match uncleanly":

https://tests.stockfishchess.org/actions?action=&user=Dantist&before=1655265828.358&count=100

This has been going on since forever. I have no idea how it is possible,

**Comment by vondele** [comment] 2022-06-15 05:03
hard to guess, would need a more detailed error message.

**Comment by silversolver1** [comment] 2022-06-16 00:13
I somehow managed to notice the "Finished match uncleanly" events from the Dantist worker happen ~15-16 minutes apart every time. MAX_RETRY_TIME in worker.py is about 15 minutes. Perhaps this is related?

**Comment by vdbergh** [comment] 2022-06-16 06:48
The matches with "Finished match uncleanly" have no games but also no crashes. This suggests that cutechess-cli failed to start the engine(s). I would be good to have access to the worker output of  Dantist-7cores-3e5ab901 so that we can see what's going on.

**Comment by vondele** [comment] 2022-06-16 06:50
@Dantist can you provide such output?

**Comment by vdbergh** [comment] 2022-06-17 08:52
@noobpwnftw Your worker ChessDBCN-16cores-f3dad03d is now suffering from throttling. See https://tests.stockfishchess.org/actions?action=&user=ChessDBCN&before=1655455764.117&count=18 .

Note: The hexadecimal number f3dad03d is the first 8 characters of the UUID (which are constant). It can be found as a comment in the config file and also in uuid.txt.

**Comment by Dantist** [comment] 2022-06-17 21:04
@vdbergh @vondele 
> This suggests that cutechess-cli failed to start the engine(s).

That actually looks correct: [run.log](https://github.com/glinscott/fishtest/files/8931082/run.log)

---
I have to say that I have a somewhat unique setup.. I planned to deploy the worker to many servers, so I dockerized it with the `alpine:edge` base image.

In general, it worked great - the latest GCC, Python, cutechess-cli (compiled from source). 
Only the worker's auto-update feature is what often broke things down (sometimes it auto-updated normally, and sometimes it pulled the cutechess-cli binary, which did not work with musl). I just had to monitor the workers and rebuild the docker image so that cutechess-cli was again compiled from the source. Sadly, I often noticed this after a few days of workers' inactivity. 
It would be cool if "the actual version of cutechess-cli was checked prior to updating" or "make this feature optional" or "verify that updated cutechess-cli binary can be executed prior to replacing the working one". 
I was occasionally reading Discord and saw that someone noticed the issue with cutechess-cli on my setup and correctly identified that my workers were running under Alpine and musl.

Anyway, currently. I see that this docker image is no longer working, and rebuilding doesn't fix the issue, and sadly enough, I have no time to fix it. Unfortunately, I haven't looked after my workers for some time and have fallen out of life, because now I have to defend my country from putin's barbaric invaders, but if I get out alive, I'll definitely fix everything.

I'll attach my docker setup below for your convenience (in troubleshooting), but you might want to amend it and add this run method as one of the option to the "Running the worker" wiki page, or even make your own official docker image and push it to hub.docker.com so people can run docker with a single CLI command without manually downloading anything. 
This should work on any OS/Arch where Docker is supported but there is a drawback - if everyone uses this method it will reduce the diversity of fishtest workers' setups.

Tiny Alpine Docker image: [fishtest-docker.zip](https://github.com/glinscott/fishtest/files/8931221/fishtest-docker.zip)

I hope this can be of any help. 
_Stay safe, take care, and send armor to Ukraine my western friends. If russia stops fighting there will be no more war. If Ukrainians stop fighting there will be no more Ukraine._

**Comment by vondele** [comment] 2022-06-17 21:08
best of luck, and stay healthy.

**Comment by ppigazzini** [comment] 2022-06-17 21:34
I wish you way more than luck @Dantist

**Comment by vdbergh** [comment] 2022-06-18 07:00
@Dantist Thanks for the logs. They are very helpful. And good luck!

**Comment by vdbergh** [comment] 2022-06-18 12:13
@noobpwnftw The worker ChessDBCN-16cores-97544138 is also suffering from throttling. See https://tests.stockfishchess.org/actions?action=&user=ChessDBCN&before=1655554389.898&count=100 .

**Comment by vdbergh** [comment] 2022-06-20 05:52
@noobpwnftw  Now the worker ChessDBCN-16cores-b858eb82 is throttled:

https://tests.stockfishchess.org/actions?action=&user=ChessDBCN&before=1655704051.324&count=100

**Comment by ppigazzini** [comment] 2022-06-26 12:02
https://tests.stockfishchess.org/actions?count=1&before=1656244248.6

See https://stackoverflow.com/questions/71580631/how-can-i-get-code-coverage-with-clang-13-0-1-on-mac

A MacOS worker is running fine with clang, perhaps has a x86_64 CPU, so at the moment skip the profiled build only for Apple silicon with #1370

**Comment by noobpwnftw** [comment] 2022-06-26 12:56
I have removed worker `f3dad03d`. Now the others seemed less frequent.

**Comment by ppigazzini** [comment] 2022-07-02 09:45
https://tests.stockfishchess.org/actions?count=1&before=1656744889.552

https://github.com/glinscott/fishtest/blob/e4b7bb596c92b401f54ed0a963ff73e0cda00b2e/worker/games.py#L819-L823

**Comment by vdbergh** [comment] 2022-07-05 18:19
@ppigazzini I have noticed this AssertionError once before. I did a code review then but could not find what might cause it. So it is a mystery. I suspect it is some kind of race condition....

**Comment by vdbergh** [comment] 2022-07-23 09:12
@noobpwnftw The worker ChessDBCN-16cores-97544138 still suffers quite heavily from throttling. See https://tests.stockfishchess.org/actions?action=&user=ChessDBCN&before=1658567399.302&count=100 .

**Comment by vdbergh** [comment] 2022-07-27 08:10
Worker technologov-28cores-r345 suffers quite badly from throttling

https://tests.stockfishchess.org/actions?action=&user=technologov&before=1658909315.519&count=100

**Comment by vdbergh** [comment] 2022-07-27 08:15
technologov-56cores-r101 suffers from "Finished match uncleanly". It plays no games so this suggests that cutechess is unable to start the engines (the same issue Dantist had, but in this case it was fixed with the new cutechess binary).

https://tests.stockfishchess.org/actions?count=1&before=1658888465.102

**Comment by ppigazzini** [comment] 2022-07-27 10:31
Here are some past analysis about the "Finished match uncleanly" problem:
https://github.com/glinscott/fishtest/pull/1110
https://github.com/glinscott/fishtest/pull/1116

**Comment by dubslow** [comment] 2022-08-02 04:34
Since it's not been discussed here, one technologov worker as well as most or every worker of linrock and sebastronomy have severe time loss problems. This is of course yet another symptom of known cutechess concurrency issues, however until the worker or cutechess is fixed, this is causing substantial pollution of fishtest data (timelosses causing higher-than-nominal pairwise-"draws", in the form of 1-0 1-0, thereby biasing test elos to 0).

See also #1393, for implementing a worker-side workaround of cutechess problems, and #1394 for server-side filtering of bad data.

**Comment by vdbergh** [comment] 2022-08-02 09:45
@dubslow This issue is specifically for documenting ill behaving workers. So it is best to refer to a worker by its full name (as has been done in the earlier comments). 

For documentation purposes it would be nice if there were a method in fishtest to link to a task (in a similar way that it is possible to link to an event). Currently we can only link to a run.

**Comment by vdbergh** [comment] 2022-08-07 06:00
A strange error started appearing with different workers "Exception FileNotFoundError at games.py:993".

https://tests.stockfishchess.org/actions?count=1&before=1659850136.108

https://tests.stockfishchess.org/actions?count=1&before=1659849265.82

(I saw many more cases).

**Comment by noobpwnftw** [comment] 2022-08-07 06:54
`97544138` removed.

**Comment by vdbergh** [comment] 2022-08-07 08:50
> `97544138` removed.

:+1:

**Comment by vdbergh** [comment] 2022-09-01 05:34
Weird errors from `ChessDBCN-16cores-24937e97`
```
Exception OSError at games.py:1129
```
https://tests.stockfishchess.org/actions?action=&user=ChessDBCN&before=1662009711.606&count=100

Line 1129 in `games.py` is
```python
        engines.sort(key=os.path.getmtime)
```
It seems that `os.path.getmtime` fails on an element of the list `engines`. It is not clear to me how this can happen (the list `engines` is made using `glob.glob`).

**Comment by vdbergh** [comment] 2022-09-01 06:52
@noobpwnftw

**Comment by ppigazzini** [comment] 2022-09-15 16:33
https://tests.stockfishchess.org/actions?count=1&before=1663254024.249
'Unable to start cutechess. Error: [WinError 206] The filename or extension is too long' could be related with the lenght of the command on Windows.

It should be a problem with the lenght of that cutechess-cli command line (over 60k characters), the maximum command line length for the Windows CreateProcess function is 32767 characters, see https://devblogs.microsoft.com/oldnewthing/20031210-00/?p=41553

```
'C:/tools/msys64/home/fishtest/worker/testing/cutechess-cli.exe', '-recover', '-repeat', '-games', '12', '-tournament', 'gauntlet', '-site', 'https://tests.stockfishchess.org/tests/view/63233ab57bd0b7ace2abc223', '-event', 'Batch 3: tunetemNF1b vs tunetemNF1b', '-srand', '1056384317', '-resign', 'movecount=3', 'score=400', '-draw', 'movenumber=34', 'movecount=8', 'score=20', '-variant', 'standard', '-concurrency', '3', '-openings', 'file=UHO_XXL_+0.90_+1.19.epd', 'format=epd', 'order=random', 'plies=16', 'start=262', '-engine', 'name=New-a8ed7c52cf', 'tc=1.632+0.016', 'cmd=stockfish_a8ed7c52cffe18e00a0224148549fbda5ea02044', 'dir=.', 'option.Hash=16', 'option.Use NNUE=true', 'option.EvalFile=nn-ad9b42354671.nnue', 'option.nw[0][0]=-4', 'option.nw[0][1]=8', 'option.nw[0][2]=-1', 'option.nw[0][3]=14', 'option.nw[0][4]=8', 'option.nw[0][5]=3', 'option.nw[0][6]=11', 'option.nw[0][7]=5', 'option.nw[0][8]=-17', 'option.nw[0][9]=20', 'option.nw[0][10]=-27', 'option.nw[0][11]=-7', 'option.nw[0][12]=22', 'option.nw[0][13]=-11', 'option.nw[0][15]=22', 'option.nw[0][16]=6', 'option.nw[0][17]=12', 'option.nw[0][18]=-25', 'option.nw[0][19]=19', 'option.nw[0][20]=-19', 
...
...
'option.nw[1][733]=-12', 'option.nw[1][734]=-21', 'option.nw[1][735]=4', 'option.nb[0]=-209', 'option.nb[1]=-476', 'option.nwo[0]=-13', 'option.nwo[1]=68', 'option.nbo=7655', '-each', 'proto=uci', 'option.Threads=1'
```

**Comment by peregrineshahin** [comment] 2022-09-16 15:15
It's very strange that the microsoft article is from *2003* and yet the length limit didn't change
Both goes for linux too
I hope we have better alternatives anyways?

**Comment by vdbergh** [comment] 2022-10-28 06:08
This error should be impossible I think with an unmodified worker… (otherwise there is a bug)

https://tests.stockfishchess.org/actions?max_actions=4&before=1666890909.8

To detect tainted workers it would be good if the worker sent its own md5sum. The server could then check this and flag a tainted worker in the worker name.

**Comment by vdbergh** [comment] 2022-10-29 08:00
I am now working on a PR where the updater saves the md5sums of the installation files. The worker can then check if it has been modified. Of course this is not a security feature. It is meant to help with debugging.

**Comment by vdbergh** [comment] 2022-10-29 18:44
Hmm it is less trivial than I thought. The worker is not always installed via the updater. So that does not really work. Computing the md5sum on the server is also tricky since the server may be running with modified worker files (during experiments).

I guess the server should download the worker files from the master branch on github but this starts getting involved (e.g. github may be down temporarily).

**Comment by vdbergh** [comment] 2022-10-30 07:47
The most convenient thing would be if a file with md5sums for the worker files were generated automatically with any PR. Is this possible? Perhaps using "github actions"? I know nothing about this but maybe someone else can help?

**Comment by vdbergh** [comment] 2022-10-30 09:09
Here is some information about changing a repository using github actions https://github.com/orgs/community/discussions/25234 .

**Comment by vdbergh** [comment] 2022-12-07 19:22
@noobpwnftw ChessDBCN-16cores-28c5c7f4 seems to have an issue. See https://tests.stockfishchess.org/actions?page=1 .

**Comment by noobpwnftw** [comment] 2022-12-07 21:44
`28c5c7f4` removed.

**Comment by vdbergh** [comment] 2022-12-07 23:20
Thanks!

**Comment by vdbergh** [comment] 2022-12-15 09:51
@noobpwnftw Worker ChessDBCN-16cores-e1b9e034 seems to have developed an issue. See https://tests.stockfishchess.org/actions?action=&user=&text="e1b9e034"+"too+slow" .

**Comment by noobpwnftw** [comment] 2022-12-15 11:33
`e1b9e034` removed.

**Comment by vdbergh** [comment] 2022-12-15 11:55
Thanks!

**Comment by vdbergh** [comment] 2022-12-17 14:44
It seems that "kdave" has an excessive number of dead tasks, all with zero games https://tests.stockfishchess.org/actions?action=dead_task&user=kdave&text=cb542585 .

**Comment by vdbergh** [comment] 2022-12-18 06:19
I wonder what would be a good strategy for dealing with badly misbehaving workers. It would be easy to block a particular worker name (like `user-abcdefgh`) and give some feedback to the user (e.g. email). However it is not clear to me how the user then should fix the problem since, being unable to connect, they cannot test if the fix works.

Of course an experienced user will know what to do, but they probably won't have issues in the first place.

**Comment by noobpwnftw** [comment] 2022-12-18 07:23
If failing workers got blocked and people would like to investigate, they can simply delete uuid.txt and try again. I don't see a problem there.

**Comment by vdbergh** [comment] 2022-12-18 08:52
We no longer use `uuid.txt` (deleting of which never had any effect BTW). The user needs to delete the `[private]` section of the config file to generate a new worker name. But as I said, experienced users would know what to do.

**Comment by ppigazzini** [comment] 2022-12-18 09:30
> I wonder what would be a good strategy for dealing with badly misbehaving workers. It would be easy to block a particular worker name (like `user-abcdefgh`) and give some feedback to the user (e.g. email). However it is not clear to me how the user then should fix the problem since, being unable to connect, they cannot test if a potential fix works.

The user could connect to DEV to investigate the problem.

**Comment by vdbergh** [comment] 2022-12-18 09:33
@ppigazzini  Great idea!!

**Comment by vdbergh** [comment] 2022-12-19 13:03
The cheapest way to proceed is to copy the user administration and adapt it to the worker level. It is simpler since there are no passwords involved. I also would not use any cache. I am sure for such simple collections mongodb can take care of any caching itself. 

In principle in the workerdb we could also put the number of games played by the workers and the amount of CPU time contributed.  But I am worried that this would create an incentive to run several workers with the same uuid prefix. I think this is probably harmless but currently we are assuming that every worker is connected at most once, except for a brief overlap between the time a worker dies and scavenging. Unfortunately this brief overlap is what makes it difficult to strictly enforce the rule of one connection per worker.

**Comment by vdbergh** [comment] 2022-12-20 06:24
@MinetaS I already reported this above. I also emailed him (got his email from github) but no response. Hence the discussion about blocking workers.

**Comment by vdbergh** [comment] 2022-12-23 13:01
Here is a modded worker https://tests.stockfishchess.org/tests/view/63a42f916b5bf07ac7fb07be?show_task=445 ...

**Comment by vdbergh** [comment] 2022-12-23 13:05
Probably a fluke because this one is also shown as modded https://tests.stockfishchess.org/tests/view/63a42f916b5bf07ac7fb07be?show_task=446 .

**Comment by ppigazzini** [comment] 2022-12-23 13:12
> Yes there are quite a few workers shown as modded. I understand why. The sri files were changed (prettifying) without a worker update. So the workers are correctly flagged as "modified".

Yes, my fault. During the `git diff master` I missed the empty line added to `worker.py` :(

**Comment by vdbergh** [comment] 2023-01-01 10:01
@MinetaS Your colab workers sometimes seem to generate an excessive number of dead tasks. See https://tests.stockfishchess.org/actions?action=dead_task&user=Mineta&text= . Normally dead tasks should only be generated after a network error on the worker's side. So it would be useful if you could tell us the corresponding output from the workers.

**Comment by MinetaS** [comment] 2023-01-01 10:07
> @MinetaS Your colab workers sometimes seem to generate an excessive number of dead tasks. See https://tests.stockfishchess.org/actions?action=dead_task&user=Mineta&text= . Normally dead tasks should only be generated after a network error on the worker's side. So it would be useful if you could tell us the corresponding output from the workers.

It's because Google terminates colab connections after approx. 7 hours.
I'm using some script to restart workers automatically once they're dead.
If the log size is excessive, I could deactivate some or all of colab instances, if that matters.

**Comment by vdbergh** [comment] 2023-01-01 10:22
> > @MinetaS Your colab workers sometimes seem to generate an excessive number of dead tasks. See https://tests.stockfishchess.org/actions?action=dead_task&user=Mineta&text= . Normally dead tasks should only be generated after a network error on the worker's side. So it would be useful if you could tell us the corresponding output from the workers.
> 
> It's because Google terminates colab connections after approx. 7 hours. I'm using some script to restart workers automatically once they're dead. If the log size is excessive, I could deactivate some or all of colab instances, if that matters.

@MinetaS No the log size is not a problem! Please continue! I was just worried that there might be a worker bug since we recently had an issue with kdave's worker that looked similar (you also reported this). But probably this was something different.

**Comment by MinetaS** [comment] 2023-01-03 15:54
leszek's worker (2996225c) has multiple time loss games in some tests.

https://tests.stockfishchess.org/tests/view/63a83922be7921cacd99ac12?show_task=293
https://tests.stockfishchess.org/tests/view/63b3b621d36022b4c6e9d8b5?show_task=115
https://tests.stockfishchess.org/tests/view/63b42f2fd7f4d54cf479b449?show_task=10
https://tests.stockfishchess.org/tests/view/63b43ec4d7f4d54cf479b5d9?show_task=1

**Comment by silversolver1** [comment] 2023-01-04 20:03
https://tests.stockfishchess.org/tests/view/63b4900dd7f4d54cf479c2fb - 902 on time

**Comment by vdbergh** [comment] 2023-01-23 09:08
@MinetaS @silversolver1 Thanks for reporting. Unfortunately there is currently not really a strategy for dealing with time losses (or other undesirable worker behavior). However since yesterday excessive time losses are recorded in the event log. This will make it easier to follow such workers. 

https://tests.stockfishchess.org/actions?action=crash_or_time&user=&text=

**Comment by vdbergh** [comment] 2023-01-24 20:34
An excessive number of time losses by Wencey-32cores

https://tests.stockfishchess.org/actions?action=crash_or_time&user=&text=%22Wencey-32cores%22

**Comment by vdbergh** [comment] 2023-01-24 21:12
I assume that the issue is that on some systems the communication between the engine and cutechess-cli steals time from the engine. There really should be an option in cutechess-cli that makes it trust the time reported by the engines. Perhaps someone can implement this?

**Comment by vdbergh** [comment] 2023-02-08 09:33
This task has more time losses than played games https://tests.stockfishchess.org/tests/view/63df697473223e7f52ad5d79?show_task=1097 

Must be a bug...

**Comment by vdbergh** [comment] 2023-04-08 06:40
@noobpwnftw Currently there are many of your workers that have the same uuid prefix which is not really desirable. I assume they were all started with a config file with the same private section. The private section looks like this:
```
[private]
hw_seed = 2564186689
```
The private section is generated once and then saved in the config file. If it is deleted then it is regenerated. The hw_seed, which is simply a random number, is the last line of defense to distinguish workers that are otherwise completely identical (e.g. running from the same virtual OS image).

**Comment by dav1312** [comment] 2023-04-20 14:23
https://tests.stockfishchess.org/actions?action=crash_or_time&user=sebastronomy
![image](https://user-images.githubusercontent.com/63931154/233395935-d3d7da19-8fa6-4dda-bcae-1d841c7e251f.png)

**Comment by vondele** [comment] 2023-04-20 14:29
I have written an email to sebastronomy.

**Comment by mcbastian** [comment] 2023-04-20 15:56
Hi, that's me. It seems to be the NUMA issue discussed a while ago on discord. I had to update kernel and OS of the machine and restarted the worker without numactl. I restarted with numactl. and will keep an eye on it.

**Comment by mcbastian** [comment] 2023-04-21 11:27
Fixed now. Faulty CPU cooling on one CPU. reduced workload on this CPU, locked the workers to certain CPU cores (numactl). No more crashes since then. Will have to call DELL to fix this. Fans all OK. looks like problem with cooler itself

**Comment by vdbergh** [comment] 2023-05-08 14:49
These workers seem to have serious issues with building SF

https://tests.stockfishchess.org/actions?action=failed_task&user=maximmasiutin&text=%22Executing+make%22%2B%22unknown+argument%22

**Comment by vondele** [comment] 2023-05-08 14:53
That's an issue that the newest clang compiler doesn't recognize one of the options we used in older versions of SF. The newer Makefile works, but not for the regression test against SF15

**Comment by vdbergh** [comment] 2023-08-11 05:13
technologov-56cores-r116 appears to be generating a large number of dead tasks

https://tests.stockfishchess.org/actions?action=dead_task&user=&text=%22technologov-56cores-r116%22

**Comment by vdbergh** [comment] 2023-08-12 19:46
technologov-56cores-r116 is still generating a large number of dead tasks. Perhaps someone can write an email?

**Comment by ppigazzini** [comment] 2023-08-12 19:51
> technologov-56cores-r116 is still generating a large number of dead tasks. Perhaps someone can write an email?
I wrote him on Discord, the user has already answered.

**Comment by vdbergh** [comment] 2023-08-23 07:31
There seem to be two workers named okrout-28cores-0a0cde5b. I.e. they have the same UUID prefix (but different UUID). This is harmless but not nice. It is also not easy to achieve accidentally.

There should be a server side mechanism to avoid duplicate UUID prefixes but is not so easy as one one has to take for example dead tasks into account which can linger for quite some time.

**Closed** 2023-08-25 21:16 UTC

**Comment by vdbergh** [comment] 2023-09-07 06:59
This worker has a problem with his make installation https://tests.stockfishchess.org/actions?action=&user=&text=+%22maximmasiutin-2cores-f21151d3%22

**Comment by vdbergh** [comment] 2023-09-07 07:37
I can block him if you give me approver rights.

**Comment by ppigazzini** [comment] 2023-09-07 07:46
> I can block him if you give me approver rights.

Done :)

**Comment by vdbergh** [comment] 2023-10-09 06:01
The strange case of [okrout-28cores-ca072243](https://tests.stockfishchess.org/actions?action=&user=&text=%22okrout-28cores-ca072243%22). 

Despite having been blocked, and having been sent an email about the blocking 3 days ago, the worker keeps dutifully reconnecting every 15 minutes, trying to get a task. 

Presumable the worker runs unattended and the email address is stale.

It is not a problem. Just strange.

**Comment by vdbergh** [comment] 2024-01-11 09:45
I suspect some users create multiple workers whose total number of cores is larger than the number of cores in the system, with predictably bad results. Perhaps this happens here https://tests.stockfishchess.org/actions?action=&user=tolkki963&text= ?

It seems feasible to count the total number of cores in use by the workers using (named) shared memory (available in Python 3.8). For Python <= 3.12 this requires a monkey patch to work around some bugs in resource tracking.

https://github.com/python/cpython/issues/82300#issuecomment-1093841376

I tested this code on python 3.10 and it works.

As usual there are two annoying issues to deal with

- workers that are terminated using SIGKILL (they are unable to clean up properly)
- synchronization

**Comment by vdbergh** [comment] 2024-01-11 10:51
Another method would be that the worker sends its local ip as well the total number of cores. Then the server can sort it out. One can get the local ip via
```pythin
import socket
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.connect(("tests.stockfishchess.org", 443))   # in general get host/port from worker arguments!
print(s.getsockname()[0])
s.close()
```
Unfortunately, using the outside IP of the worker does not work because of NAT.

**Comment by vdbergh** [comment] 2024-01-11 11:38
I am thinking that is easier for the server to sort it out (if the workers send the necessary information).

The server needs to know which workers run on the same machine but this can be done by using a random number in some fixed temporary file.
