### ISSUE TITLE
flawed duplicate workers detections that is detrimintal to some workers

### ISSUE THREAD

**Issue by peregrineshahin** [official-stockfish/fishtest#1976] opened 2024-05-02 14:20 UTC
First of all, sleeps and timeouts are used to prevent the making of duplicate workers on the client side which as the comment also indicates does not work on slow systems (maybe bad idea?).
it can even on a single machine be prone to error and will cause issues.

Now the bigger issue is that we depend on the heartbeat code on the worker side which is set to 120
and on the server side we *assign* `last_updated` which does not take into account how slow the request came to the server and how slow our server code is before assigning that ` task["last_updated"] = datetime.now(timezone.utc)`

this means that if one request took 3 seconds to reach the server with some payload, and our server took 1s to validate it and assign a last_updated time to it, then if the second consecutive request took less time to reach the server, we will have a delta of <= 120 and thus a false alarm about duplicate workers that can kill lots of cores and drive them into a loop.

Related Code:

https://github.com/official-stockfish/fishtest/blob/75a5dc62a00ce61bd44603f330edbc516175d35f/worker/worker.py#L1514-L1521

https://github.com/official-stockfish/fishtest/blob/75a5dc62a00ce61bd44603f330edbc516175d35f/worker/worker.py#L1168-L1197

https://github.com/official-stockfish/fishtest/blob/75a5dc62a00ce61bd44603f330edbc516175d35f/server/fishtest/api.py#L604-L611

https://github.com/official-stockfish/fishtest/blob/75a5dc62a00ce61bd44603f330edbc516175d35f/server/fishtest/rundb.py#L862-L877

**Comment by vdbergh** [comment] 2024-05-02 14:31
This problem occurs when a worker disconnects with `kill -9` (instead of using SIGTERM). In that case the worker cannot inform the server of the disconnection and from the server's point of view the worker is still working on a task (after a looong time the task will be scavenged).

We don't want workers with duplicate names so the server will prevent the worker from reconnecting for some time. But after some time without updates from the original worker, it has to decide that the original worker is probably dead. 120 seconds (the heartbeat period) seems like a good compromise. It is a tradeoff between convenience and accuracy.

**Comment by vdbergh** [comment] 2024-05-02 15:25
Well it's not a bug AFAICS but expected behavior....

**Comment by peregrineshahin** [comment] 2024-05-02 15:35
I can't follow much how all these stuff are related, but I have two concerns:
1- if there can be asynchronous handling to issues that we tackle now with delays.
2- if the math does not add up because request time is not account for leading to irreversible situation.

But from what I can tell, your reply suggests that even with the thought experiments I presented, duplicate worker false positive is reversable..

**Comment by vdbergh** [comment] 2024-05-02 15:46
> I can't follow much how all these stuff are related, but I have two concerns: 1- if there can be asynchronous handling to issues that we tackle now with delays. 2- if the math does not add up because request time is not account for leading to irreversible situation.
> 
> But from what I can tell, your reply suggests that even with the thought experiments I presented, duplicate worker false positive is reversable..

I don't really understand what you are saying. The 120 seconds is only a heuristic. It does not need to be precise. We do not need an ironclad 100% mathematical guarantee that workers with duplicate names can never connect simultaneously. Workers with duplicate names are handled fine by the server. But we want to avoid it as much as possible because we want to be able to identify individual workers for the worker administration. 

If you reject the current solution then please tell me how to handle what I wrote above and what I will repeat here:

> So the problem is to distinguish between people that genuinely use workers with duplicate names (like noob used to do at one point I think) and people that brutally disconnect their worker. You want to prevent the first without too much punishing the second.

**Comment by ppigazzini** [comment] 2024-05-02 15:57
> Well it's not a bug AFAICS but expected behavior....

We are routinely taking down some workers fleets, IMO we didn't expect that.

<details><summary>Click to view</summary>

Apr 24 22:22:38 tests.stockfishchess.org systemd[1]: Stopping Fishtest Server port 6543...
Apr 24 22:22:38 tests.stockfishchess.org pserve[19678]: flush
Apr 24 22:22:39 tests.stockfishchess.org pserve[19678]: ...........................done
Apr 24 22:22:40 tests.stockfishchess.org systemd[1]: Stopped Fishtest Server port 6543.
Apr 24 22:22:40 tests.stockfishchess.org systemd[1]: Started Fishtest Server port 6543.
Apr 24 22:22:41 tests.stockfishchess.org pserve[24847]: Starting server in PID 24847.
Apr 24 22:22:53 tests.stockfishchess.org pserve[24847]: Request_task: no useful cached runs left
Apr 24 22:22:53 tests.stockfishchess.org pserve[24847]: Request_task: refresh queue
Apr 24 22:24:17 tests.stockfishchess.org pserve[24847]: Request_task: refresh queue
Apr 24 22:24:52 tests.stockfishchess.org pserve[24847]: Request_task: refresh queue
Apr 24 22:26:00 tests.stockfishchess.org pserve[24847]: Request_task: refresh queue
Apr 24 22:26:50 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 70 seconds ago
Apr 24 22:27:15 tests.stockfishchess.org pserve[24847]: Request_task: refresh queue
Apr 24 22:28:16 tests.stockfishchess.org pserve[24847]: Request_task: refresh queue
Apr 24 22:28:27 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-6cores-651c1fe4" which sent an update 86 seconds ago
Apr 24 22:28:46 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 50 seconds ago
Apr 24 22:29:00 tests.stockfishchess.org pserve[24847]: dead task: run: https://tests.stockfishchess.org/tests/view/662954f43fe04ce4cefc7c44 task_id: 7 worker: linrock-16cores-2de1f361-46f4
Apr 24 22:29:29 tests.stockfishchess.org pserve[24847]: dead task: run: https://tests.stockfishchess.org/tests/view/66293d2a3fe04ce4cefc7a5f task_id: 82 worker: technologov-28cores-r323-8f93
Apr 24 22:29:31 tests.stockfishchess.org pserve[24847]: dead task: run: https://tests.stockfishchess.org/tests/view/66294c483fe04ce4cefc7b8e task_id: 16 worker: sebastronomy-31cores-6b074983-9f72
Apr 24 22:29:33 tests.stockfishchess.org pserve[24847]: Request_task: refresh queue
Apr 24 22:29:42 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 106 seconds ago
Apr 24 22:30:13 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-638d062c" which sent an update 58 seconds ago
Apr 24 22:30:19 tests.stockfishchess.org pserve[24847]: dead task: run: https://tests.stockfishchess.org/tests/view/66293d2a3fe04ce4cefc7a5f task_id: 83 worker: linrock-16cores-3189cd22-0ee3
Apr 24 22:30:37 tests.stockfishchess.org pserve[24847]: dead task: run: https://tests.stockfishchess.org/tests/view/662953453fe04ce4cefc7c24 task_id: 8 worker: magicsam82-1cores-22616ebf-5759
Apr 24 22:30:37 tests.stockfishchess.org pserve[24847]: dead task: run: https://tests.stockfishchess.org/tests/view/662953453fe04ce4cefc7c24 task_id: 9 worker: markkulix-2cores-AMD5600G-7873
Apr 24 22:30:38 tests.stockfishchess.org pserve[24847]: Request_task: refresh queue
Apr 24 22:30:38 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-2f97af89" which sent an update 60 seconds ago
Apr 24 22:31:11 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-638d062c" which sent an update 116 seconds ago
Apr 24 22:31:16 tests.stockfishchess.org pserve[24847]: dead task: run: https://tests.stockfishchess.org/tests/view/662681c63fe04ce4cefc4c10 task_id: 229 worker: linrock-16cores-1b4d8063-408c
Apr 24 22:31:24 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-2f97af89" which sent an update 106 seconds ago
Apr 24 22:31:33 tests.stockfishchess.org pserve[24847]: dead task: run: https://tests.stockfishchess.org/tests/view/662803213fe04ce4cefc6626 task_id: 112 worker: linrock-16cores-df5bf3a4-e883
Apr 24 22:31:37 tests.stockfishchess.org pserve[24847]: dead task: run: https://tests.stockfishchess.org/tests/view/662953453fe04ce4cefc7c24 task_id: 11 worker: linrock-16cores-73b62fda-89af
Apr 24 22:31:43 tests.stockfishchess.org pserve[24847]: Request_task: refresh queue
Apr 24 22:31:50 tests.stockfishchess.org pserve[24847]: dead task: run: https://tests.stockfishchess.org/tests/view/662985863fe04ce4cefc7fb6 task_id: 0 worker: ChessDBCN-6cores-651c1fe4-8bec
Apr 24 22:31:50 tests.stockfishchess.org pserve[24847]: dead task: run: https://tests.stockfishchess.org/tests/view/662985863fe04ce4cefc7fb6 task_id: 1 worker: CypressChess-8cores-43326511-38cc
Apr 24 22:31:50 tests.stockfishchess.org pserve[24847]: dead task: run: https://tests.stockfishchess.org/tests/view/662985863fe04ce4cefc7fb6 task_id: 2 worker: oz-16cores-bdc66c0b-1c1c
Apr 24 22:32:21 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 70 seconds ago
Apr 24 22:32:22 tests.stockfishchess.org pserve[24847]: dead task: run: https://tests.stockfishchess.org/tests/view/6628d1aa3fe04ce4cefc73c5 task_id: 65 worker: ChessDBCN-11cores-ccd4f156-3dff
Apr 24 22:32:25 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-e64bd59b" which sent an update 54 seconds ago
Apr 24 22:32:36 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-638d062c" which sent an update 50 seconds ago
Apr 24 22:32:40 tests.stockfishchess.org pserve[24847]: dead task: run: https://tests.stockfishchess.org/tests/view/662602803fe04ce4cefc43b1 task_id: 241 worker: xuhdev-1cores-4bd11645-cda4
Apr 24 22:32:40 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-6cores-651c1fe4" which sent an update 107 seconds ago
Apr 24 22:32:45 tests.stockfishchess.org pserve[24847]: Request_task: refresh queue
Apr 24 22:33:04 tests.stockfishchess.org pserve[24847]: dead task: run: https://tests.stockfishchess.org/tests/view/66270e383fe04ce4cefc55cb task_id: 231 worker: quildtide-3cores-fe3d0006-2f74
Apr 24 22:33:04 tests.stockfishchess.org pserve[24847]: dead task: run: https://tests.stockfishchess.org/tests/view/66270e383fe04ce4cefc55cb task_id: 232 worker: OliverClarke-4cores-77f5f8d1-fb9c
Apr 24 22:33:07 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-2f97af89" which sent an update 57 seconds ago
Apr 24 22:33:07 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-57fd25b6" which sent an update 73 seconds ago
Apr 24 22:33:22 tests.stockfishchess.org pserve[24847]: dead task: run: https://tests.stockfishchess.org/tests/view/6628d1aa3fe04ce4cefc73c5 task_id: 66 worker: javran-8cores-baab49a9-0a64
Apr 24 22:33:28 tests.stockfishchess.org pserve[24847]: dead task: run: https://tests.stockfishchess.org/tests/view/662671383fe04ce4cefc4ae5 task_id: 256 worker: ChessDBCN-6cores-651c1fe4-5acd
Apr 24 22:33:33 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-638d062c" which sent an update 107 seconds ago
Apr 24 22:33:52 tests.stockfishchess.org pserve[24847]: dead task: run: https://tests.stockfishchess.org/tests/view/662797ae3fe04ce4cefc5eb0 task_id: 192 worker: maposora-4cores-d52d7f50-c513
</details>

<details><summary>Click to view</summary>

May 02 04:12:48 tests.stockfishchess.org pserve[27841]: Request_task: refresh queue
May 02 04:13:50 tests.stockfishchess.org pserve[27841]: Request_task: refresh queue
May 02 04:15:20 tests.stockfishchess.org pserve[27841]: Request_task: refresh queue
May 02 04:16:25 tests.stockfishchess.org pserve[27841]: Request_task: refresh queue
May 02 04:17:13 tests.stockfishchess.org pserve[27841]: Request_task: There is already a worker running with name "technologov-32cores-amd3990x" which sent an update 73 seconds ago
May 02 04:17:27 tests.stockfishchess.org pserve[27841]: Request_task: refresh queue
May 02 04:17:27 tests.stockfishchess.org pserve[27841]: Request_task: There is already a worker running with name "technologov-28cores-r301" which sent an update 89 seconds ago
May 02 04:17:28 tests.stockfishchess.org pserve[27841]: Request_task: There is already a worker running with name "technologov-28cores-r304" which sent an update 113 seconds ago
May 02 04:17:28 tests.stockfishchess.org pserve[27841]: Request_task: There is already a worker running with name "technologov-28cores-r309" which sent an update 83 seconds ago
May 02 04:17:29 tests.stockfishchess.org pserve[27841]: Request_task: There is already a worker running with name "technologov-32cores-amd3990x" which sent an update 88 seconds ago
May 02 04:17:29 tests.stockfishchess.org pserve[27841]: Request_task: There is already a worker running with name "technologov-28cores-r305" which sent an update 90 seconds ago
May 02 04:17:30 tests.stockfishchess.org pserve[27841]: Request_task: There is already a worker running with name "technologov-28cores-r303" which sent an update 119 seconds ago
May 02 04:17:32 tests.stockfishchess.org pserve[27841]: Request_task: There is already a worker running with name "technologov-28cores-r307" which sent an update 99 seconds ago
May 02 04:17:32 tests.stockfishchess.org pserve[27841]: Request_task: There is already a worker running with name "technologov-28cores-r314" which sent an update 109 seconds ago
May 02 04:17:34 tests.stockfishchess.org pserve[27841]: Request_task: There is already a worker running with name "technologov-28cores-r300" which sent an update 91 seconds ago
May 02 04:17:35 tests.stockfishchess.org pserve[27841]: Request_task: There is already a worker running with name "technologov-28cores-r302" which sent an update 99 seconds ago
May 02 04:17:36 tests.stockfishchess.org pserve[27841]: Request_task: There is already a worker running with name "technologov-28cores-r308" which sent an update 115 seconds ago
May 02 04:17:43 tests.stockfishchess.org pserve[27841]: Request_task: There is already a worker running with name "technologov-28cores-r301" which sent an update 104 seconds ago
May 02 04:17:44 tests.stockfishchess.org pserve[27841]: Request_task: There is already a worker running with name "technologov-28cores-r309" which sent an update 99 seconds ago
May 02 04:17:45 tests.stockfishchess.org pserve[27841]: Request_task: There is already a worker running with name "technologov-28cores-r305" which sent an update 106 seconds ago
May 02 04:17:47 tests.stockfishchess.org pserve[27841]: Request_task: There is already a worker running with name "technologov-28cores-r307" which sent an update 115 seconds ago
May 02 04:17:49 tests.stockfishchess.org pserve[27841]: Request_task: There is already a worker running with name "technologov-28cores-r300" which sent an update 106 seconds ago
May 02 04:17:51 tests.stockfishchess.org pserve[27841]: Request_task: There is already a worker running with name "technologov-28cores-r302" which sent an update 115 seconds ago
May 02 04:17:59 tests.stockfishchess.org pserve[27841]: Request_task: There is already a worker running with name "technologov-32cores-amd3990x" which sent an update 119 seconds ago
May 02 04:18:32 tests.stockfishchess.org pserve[27841]: Request_task: refresh queue
</details>

**Comment by peregrineshahin** [comment] 2024-05-02 16:00
> We are routinely taking down some workers fleets, IMO we didn't expect that.

Because it seemingly doesn't work.
This might need a big think for an alternative.

**Comment by vdbergh** [comment] 2024-05-02 16:05
To understand this one would need to know these fleets react to a server restart. Normally a short server restart is transparent to the worker. It should not trigger a reconnect.

Note that if a worker is prevented from connecting because the server thinks a duplicate worker is present, this error is non fatal. The worker will sleep for a bit and retry. Did anyone actually complain?

**Comment by ppigazzini** [comment] 2024-05-02 16:11
![image](https://github.com/official-stockfish/fishtest/assets/15718418/066e22a5-3e94-412e-ba00-4fe11bafbb63)

This was triggered by the server restart when merging this https://github.com/official-stockfish/fishtest/pull/1952
The restart took the usual 2-5 seconds.

**Comment by vdbergh** [comment] 2024-05-02 16:19
Is there a server log corresponding to this complaint of Sebastronomy. It seems it can have any number of cases.

> The fist log is about the issue triggered by the server restart when merging this https://github.com/official-stockfish/fishtest/pull/1952

Yes but I do not know how these fleets handle server restarts. They may have unconventional setups.  People having non-standard setups are expected to be experts that understand what they are doing. As I said, if reconnection is spuriously denied, then this is a non-fatal error.

**Comment by vdbergh** [comment] 2024-05-02 16:20
> > We are routinely taking down some workers fleets, IMO we didn't expect that.
> 
> Because it seemingly doesn't work. This might need a big think for an alternative.

Why do you say it does not work? It achieves precisely what I wrote. Of course there may be better solutions and I would certainly we willing to hear about them,

**Comment by vdbergh** [comment] 2024-05-02 16:27
Ok. From the first log.
```
Apr 24 22:26:50 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 70 seconds ago
Apr 24 22:28:46 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 50 seconds ago
Apr 24 22:29:42 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 106 seconds ago
Apr 24 22:32:21 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 70 seconds ago
```
I think this is not supposed to happen. Either noob is really running a duplicate worker, or else there might be indeed a bug. I will think about it.

**Comment by ppigazzini** [comment] 2024-05-02 16:27
The first issue could be due my bug slip, with all fleets configured to restart if the worker is stopping for a fatal exception.
The workers stopped being rejected after merging the fix https://github.com/official-stockfish/fishtest/pull/1953

**Comment by vdbergh** [comment] 2024-05-02 16:40
@ppigazzini Do you see other duplication warnings for this worker "ChessDBCN-11cores-ccd4f156" outside server restarts?

**Comment by ppigazzini** [comment] 2024-05-02 16:40
```
sudo journalctl -u fishtest@6543 --since "30 days ago" | grep "is already a worker" | wc -l
652
```
Mostly ""ChessDBCN" and "technologov", but there are at least a dozen of other workers

**Comment by ppigazzini** [comment] 2024-05-02 16:41
> @ppigazzini Do you see other duplication warnings for this worker "ChessDBCN-11cores-ccd4f156" outside server restarts?

```yaml
sudo journalctl -u fishtest@6543 --since "30 days ago" | grep "is already a worker" | grep "ChessDBCN-11cores-ccd4f156"
Apr 08 09:28:25 tests.stockfishchess.org pserve[25518]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 80 seconds ago
Apr 08 09:28:56 tests.stockfishchess.org pserve[25518]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 111 seconds ago
Apr 24 04:10:20 tests.stockfishchess.org pserve[19678]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 91 seconds ago
Apr 24 22:26:50 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 70 seconds ago
Apr 24 22:28:46 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 50 seconds ago
Apr 24 22:29:42 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 106 seconds ago
Apr 24 22:32:21 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 70 seconds ago
Apr 24 22:34:19 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 59 seconds ago
Apr 24 22:35:13 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 113 seconds ago
Apr 24 22:37:12 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 59 seconds ago
Apr 24 22:39:02 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 42 seconds ago
Apr 24 22:39:53 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 93 seconds ago
Apr 24 22:42:57 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 90 seconds ago
Apr 24 22:45:14 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 99 seconds ago
Apr 24 22:48:17 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 81 seconds ago
Apr 24 22:48:51 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 115 seconds ago
Apr 24 22:50:19 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 43 seconds ago
Apr 24 22:51:25 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 110 seconds ago
```

**Comment by vdbergh** [comment] 2024-05-02 16:44
Maybe we should check with @noobpwnftw to make sure he does not have two workers with the name "ChessDBCN-11cores-ccd4f156" (I suspect not since then I think the warning would be much more frequent).

**Comment by ppigazzini** [comment] 2024-05-02 16:48
IMO the issue is triggered in some way by a lan connection loss/retard, VPS side or workers side.
The issue of the 24 April was due at 99% by my bug and the fleet set to restart the workers.

**Comment by peregrineshahin** [comment] 2024-05-02 17:02
Could we at least implement a mechanism that feedbacks from the server to the worker and changes its abusive name instead of rejecting him?

**Comment by ppigazzini** [comment] 2024-05-02 17:11
The server temporary rejects 23-26 workers/day, perhaps on Discord people is overreacting a bit. 
```
sudo journalctl -u fishtest@6543 --since "180 days ago" | grep "is already a worker" | wc -l
4139
sudo journalctl -u fishtest@6543 --since "210 days ago" | grep "is already a worker" | wc -l
5540
```

**Comment by peregrineshahin** [comment] 2024-05-02 17:25
Well this doesn't mean that we can't enhance stuff even if it's an outlier... IMO rejecting duplicate workers makes no sense... we can feedback and rename each one to some random name ... 

> The server temporary rejects 23-26 duplicated workers/day, perhaps on Discord people is overreacting a bit.
> 
> ```
> sudo journalctl -u fishtest@6543 --since "180 days ago" | grep "is already a worker" | wc -l
> 4139
> sudo journalctl -u fishtest@6543 --since "210 days ago" | grep "is already a worker" | wc -l
> 5540
> ```

**Comment by vdbergh** [comment] 2024-05-02 17:28
I suspect that most of these are explainable by people brutally killing the worker, or perhaps by some interaction at server restart.

However this I cannot explain:
```
Apr 24 22:26:50 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 70 seconds ago
Apr 24 22:28:46 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 50 seconds ago
Apr 24 22:29:42 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 106 seconds ago
Apr 24 22:32:21 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 70 seconds ago
```
The update time should go up until it is above 120  and then the worker should connect. I need to check if there is another way in which the last updated field in a worker can change, besides the beat api.

**Comment by ppigazzini** [comment] 2024-05-02 17:35
The bug killed the worker when requesting a new task, some code auto restarted the worker. The duplicated worker issue of the 24 April disappeared after merging the bugfix.

**Comment by vdbergh** [comment] 2024-05-02 17:40
OMG. It seems `task["last_updated"]` is updated in `tests_view`. That explains it!

**Comment by peregrineshahin** [comment] 2024-05-02 17:46
What is beyond me is that we use last_updated which is a server field to determine a work feature.. whereas we code just send with the payload when did the worker send stuff.. i.e. why do we even need heuristics?

**Comment by vdbergh** [comment] 2024-05-02 17:48
```
Apr 24 22:26:50 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 70 seconds ago
Apr 24 22:28:46 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 50 seconds ago
Apr 24 22:29:42 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 106 seconds ago
Apr 24 22:32:21 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 70 seconds ago
```
Perhaps the worker actually succeeded in connecting and then became itself incommunicado, blocking the next connection attempt and to on.

To be able to debug this we need to print the full worker name in the message.  I will make a PR.

**Comment by vdbergh** [comment] 2024-05-02 17:49
> What is beyond me is that we use last_updated which is a server field to determine a work feature.. whereas we could just send with the payload when did the worker send stuff.. i.e. why do we even need heuristics?

I agree this is very wrong but I am not responsible for that code (at least I don't think so).

**Comment by peregrineshahin** [comment] 2024-05-02 17:51
Well this goes also for the 120s thing in detecting the duplicate worker Im not only talking about test view

**Comment by ppigazzini** [comment] 2024-05-02 17:52
Unfortunately, this should explain the low core count...
![image](https://github.com/official-stockfish/fishtest/assets/15718418/cdf1b3b5-0519-4e0a-bd03-e901912ef665)

**Comment by peregrineshahin** [comment] 2024-05-02 17:58
I agree that it has most of its use.. we should ofc not accept such information from the worker it might tell that it was last_updated before 1970, but IMO it's perfect to have both, last_updated and worker_submission_time. According to itself and according to the world... some Kantianism maybe :p.

**Comment by peregrineshahin** [comment] 2024-05-03 03:05
Btw I already showcased in my thought experiment how the duplicate worker detection can happen for the same exact worker, I didn't bring up any theories that this happens because of killing the worker.
But not sure what we can deduce from knowing that except that the detection itself could be improved if thats true..

**Comment by peregrineshahin** [comment] 2024-05-03 11:52
Suggested solution for all the issues related to duplication and maintain the blocking worker system:

The easiest is
1) Allow the exact same worker to pass this duplicate testing as per the assigned part of the full worker name
2) Whenever we flag the worker as duplicated but not exact, return an error in the post request for the worker to forcefully change its name to some random stuff.

**Comment by peregrineshahin** [comment] 2024-05-03 12:03
Please let me know if I should code it

**Comment by peregrineshahin** [comment] 2024-05-03 13:40
Sorry I forgot to tell you that we should never depend on delays and timeouts, I would change worker ugly the random ugly worker names `s34fsw4` any day all day over preventing them from doing work and making them get into a closed loop.
That being said there are many solutions, one of them is to ask the server for a name, we can ticketize/tockenize the names.
The amount of solutions are inifnite, I'm glad that you agree finally that there is a problem `The duplicate worker messages are almost always false positives.`

**Comment by vdbergh** [comment] 2024-07-04 14:16
I would propose to close this. The server simply does the best it can to avoid different workers connecting with the same name.

**Closed** 2024-08-19 05:21 UTC
Labels: bug
