### ISSUE TITLE
non-ascii paths.

### ISSUE THREAD

**Issue by vondele** [official-stockfish/fishtest#1230] opened 2022-01-07 15:14 UTC
an exchange in discord about a crashing worker  getraideBFF https://tests.stockfishchess.org/tests/view/61d800f1f5fd40f357469b0a revealed that that worker was running into https://github.com/official-stockfish/Stockfish/issues/3424 

This can't be easily fixed in SF, but maybe the worker code detect the fact it is running in a path that contains non-ascii characters (cyrillic) and detect it?

**Comment by vondele** [comment] 2022-01-07 15:17
I've documented this limitation here https://github.com/glinscott/fishtest/wiki/Running-the-worker:-overview#install-the-worker

**Comment by vdbergh** [comment] 2022-01-07 15:26
I am curious. Why can SF not handle non-ascii strings?

**Comment by vdbergh** [comment] 2022-01-07 15:32
I guess it is a windows problem. Windows cannot handle UTF-8 path names (the most common encoding on the planet).  So one has to convert first to UTF-16.

First result on Google https://stackoverflow.com/questions/7153935/how-to-convert-utf-8-stdstring-to-utf-16-stdwstring

**Comment by vondele** [comment] 2022-01-07 15:42
yes, and the SF code needs to use the right types for filenames in all places etc... it is definitely not completely trivial to get right.

**Comment by vdbergh** [comment] 2022-01-07 15:50
The worker could send the short path name to SF: https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getshortpathnamew .

**Comment by vondele** [comment] 2022-01-07 15:53
I think it is not worth trying to do it from the worker. Things in SF it self might break (like it searches for the net in a couple of directories).

**Comment by vdbergh** [comment] 2022-01-07 15:56
Ok. Not allowing asci paths in filenames probably excludes a sizable part of the world's population though. Nowadays people expect unicode to "just work".

**Comment by vondele** [comment] 2022-01-07 15:58
yes, I agree, so well tested patches for SF would be welcome there :-) 
For whatever reason the Lc0 people said it is really non-trivial, so I take their word for it.

**Comment by vdbergh** [comment] 2022-01-07 16:10
I really think this is fixable on the worker's side. This is the cuplrit
```
option.EvalFile=/home/fishtest/fishtest/worker/testing/nn-13406b1dcbe0.nnue
```
The current directory is `/home/fishtest/fishtest/worker/testing`. So there doesn't seem to be any need to supply a path at all.

**Comment by vondele** [comment] 2022-01-07 16:11
OK, if that fixes it, I'm of course fine with it.

**Comment by vdbergh** [comment] 2022-01-07 16:15
Where is the code in SF that searches for the net?

**Comment by vdbergh** [comment] 2022-01-07 16:20
```
vector<string> dirs = { "<internal>" , "" , CommandLine::binaryDirectory , stringify(DEFAULT_NNUE_DIRECTORY) };
```
If I interpret this correctly it will first search in the current directory. Which is what we want.

**Comment by vondele** [comment] 2022-01-07 16:23
it will first use the embedded net, after that
it will search the directory of the binary.... that would probably go wrong.

**Comment by vdbergh** [comment] 2022-01-07 16:24
No, the empty string "" is in the second place. That should be the current directory.

**Comment by vondele** [comment] 2022-01-07 16:28
sorry, right...

**Comment by vdbergh** [comment] 2022-01-07 17:20
If it doesn't work we can also embed the net (first copy the downloaded/cached net to the build directory).

**Comment by vondele** [comment] 2022-01-07 19:25
we specifically didn't do that since that would make the cache of the binaries large in size.

**Comment by vdbergh** [comment] 2022-01-08 05:59
It is fixed on the worker’s side now. However it might still be a good idea to trace the cause of the crash in SF and print an error message instead. Some system call used by SF must return with an error.

**Comment by vdbergh** [comment] 2022-01-08 07:42
I guess SF doesn't actually crash but just doesn't find the net and then exits. That would be perfectly fine of course.

**Comment by vondele** [comment] 2022-01-08 07:54
I think that's what happens, but can't test.

**Comment by vdbergh** [comment] 2024-07-04 14:31
This was fixed. Can be closed.

**Closed** 2024-07-04 14:59 UTC
Labels: bug, worker update
